Repository ably/ably-python, pull requests merged in 2023-03, with the labels that each got.

#474 RSN4b Compliance
  ably/rest/channel.py
  test/ably/rest/restchannels_test.py
Labels: breaking

#479 Update README to mention token-based authentication support
  README.md
Labels: documentation

#482 Remove deprecated APIs
  ably/rest/auth.py
  ably/rest/channel.py
  ably/types/options.py
  ably/util/crypto.py
  test/ably/realtime/realtimeconnection_test.py
  test/ably/rest/restauth_test.py
  test/ably/rest/restchannelhistory_test.py
  test/ably/rest/restchannelpublish_test.py
  test/ably/rest/resthttp_test.py
  test/ably/rest/restinit_test.py
  test/ably/rest/restrequest_test.py
  test/ably/testapp.py
Labels: breaking

#399 RSC7c
  ably/http/http.py
  ably/http/httputils.py
  ably/types/options.py
  test/ably/resthttp_test.py
Labels: enhancement
